version: "3.9"
services:
        backend:
                container_name: backend_tr
                image: backend:v1.0
                tty: true
                build: docker/backend
                ports:
                  - 8080:3000
                networks:
                       - ft_transcendence
                restart: on-failure
                volumes:
                        - ./backend:/var/www/html
        frontend_gc_test:
          container_name: frontend_gc_test
          image: frontend_gc_test
          tty: true
          build: docker/frontend/gchopin
          ports:
            - 8081:3000
          networks:
            - ft_transcendence
          restart: on-failure
          volumes:
            - ./frontend/gchopin:/var/www/html

networks:
        ft_transcendence:
