version: "3.9"
services:
        backend:
                container_name: backend_tr
                image: backend:v1.0
                tty: true
                build: docker/backend
                ports:
                  - 5000:3000
                networks:
                       - ft_transcendence
                restart: on-failure
                volumes:
                        - ./backend:/var/www/html
        frontend_tr:
          container_name: frontend_tr
          image: frontend
          tty: true
          build: docker/frontend
          ports:
            - 5173:5173
          networks:
            - ft_transcendence
          restart: on-failure
          volumes:
            - ./frontend:/var/www/html

        postgres_tr:
          container_name: postgres_tr
          image: db
          tty: true
          build: docker/db
          restart: on-failure
          volumes:
            - db:/var/lib/postgresql/data
          ports:
                  - "5432:5432"
          networks:
            - ft_transcendence

        adminer:
                container_name: adminer
                image: adminer:v1.0
                tty: true
                build: docker/adminer
                ports:
                  - "9002:80"
                networks:
                        - ft_transcendence
                volumes:
                        - db:/var/lib/postgresql/data
                        - ./frontend:/var/www/html
                restart: on-failure
                depends_on:
                  - "postgres_tr"

volumes:
 db:
networks:
        ft_transcendence:
