version: "3.9"
services:
        backend:
                container_name: backend_tr
                image: backend:v1.0
                tty: true
                build: docker/backend
                ports:
                  - 5000:3000
                networks:
                       - ft_transcendence
                restart: on-failure
                volumes:
                        - ./backend:/var/www/html
        frontend_tr:
          container_name: frontend_tr
          image: frontend
          tty: true
          build: docker/frontend
          ports:
            - 5173:5173
          networks:
            - ft_transcendence
          restart: on-failure
          volumes:
            - ./frontend:/var/www/html

        postgres:
          image: postgres
          restart: always
          environment:
           POSTGRES_PASSWORD: root
           POSTGRESQL_POSTGRES_PASSWORD: root
          volumes:
            - db:/var/lib/postgresql/data
          ports:
            - 5432:5432

        adminer:
            image: adminer
            restart: always
            ports:
               - 8080:8080

volumes:
 db:
networks:
        ft_transcendence:
