version: "3.9"
services:
        backend:
                container_name: backend_tr
                image: backend:v1.0
                tty: true
                build: docker/backend
                ports:
                  - 8080:3000
                networks:
                       - ft_transcendence
                restart: on-failure
                volumes:
                        - ./backend:/var/www/html
        frontend_tr:
          container_name: frontend_tr
          image: frontend
          tty: true
          build: docker/frontend
          ports:
            - 5173:5173
          networks:
            - ft_transcendence
          restart: on-failure
          volumes:
            - ./frontend:/var/www/html

networks:
        ft_transcendence:
